// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[ENV] Supabase not configured. Functionalities dependent on Supabase will be disabled in dev.');
}

/**
 * A flag to indicate if the Supabase client is properly configured with credentials.
 * Components can use this to render fallback UI or disable features.
 * It checks if the URL and key are present and don't contain placeholders.
 */
export const supabaseReady = !!(
  supabaseUrl &&
  !supabaseUrl.includes('PLACEHOLDER') &&
  supabaseAnonKey &&
  !supabaseAnonKey.includes('PLACEHOLDER')
);

/**
 * The Supabase client instance.
 * It will be `null` if the environment variables are not set or are placeholders.
 * Always check `supabaseReady` or `if (supabase)` before using the client.
 */
export const supabase: SupabaseClient<Database> | null =
  supabaseReady
    ? createClient<Database>(supabaseUrl, supabaseAnonKey, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : null;