// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esgkwpfjvltmrqvyqker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZ2t3cGZqdmx0bXJxdnlxa2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTI4ODUsImV4cCI6MjA3MDA4ODg4NX0.O3qzch8Tbu845XV2_f3onXT0h-_Xd1KTY48Ct4a03pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});